version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                uid: ${UID}
        container_name: app
        ports:
            - "8000:80"
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - app

    app-db:
        image: mysql:8.0
        container_name: app-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            backend:
                aliases:
                    - app-db

networks:
    backend:
        name: backend-network
