version: '3.8'

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/virtual-host.conf:/etc/apache2/sites-enabled/virtual-host.conf
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        depends_on:
            - app-db
        networks:
            app-network:
                aliases:
                    - app
    app-db:
        image: mysql:8.0
        container_name: app-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=panda
            - MYSQL_USER=panda_app
            - MYSQL_PASSWORD=
        networks:
            app-network:
                aliases:
                    - db
networks:
    app-network:
        name: backend
